// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJIrg7FEiBiasnA2hbhzrB_Bk_NjCqWSM',
    appId: '1:207018206449:web:3959687d5107f31a017550',
    messagingSenderId: '207018206449',
    projectId: 'heart-rate-879b0',
    authDomain: 'heart-rate-879b0.firebaseapp.com',
    databaseURL: 'https://heart-rate-879b0-default-rtdb.firebaseio.com',
    storageBucket: 'heart-rate-879b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5JMsYi8XXqGfDZym4cX1Ixz7_Cw_gvpI',
    appId: '1:207018206449:android:b7daee0e4a614226017550',
    messagingSenderId: '207018206449',
    projectId: 'heart-rate-879b0',
    databaseURL: 'https://heart-rate-879b0-default-rtdb.firebaseio.com',
    storageBucket: 'heart-rate-879b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_f5jk8_VXCfYUY9kzOF3aE95EdpqI2YI',
    appId: '1:207018206449:ios:64dd45175daa9ac4017550',
    messagingSenderId: '207018206449',
    projectId: 'heart-rate-879b0',
    databaseURL: 'https://heart-rate-879b0-default-rtdb.firebaseio.com',
    storageBucket: 'heart-rate-879b0.firebasestorage.app',
    iosBundleId: 'com.example.seizrureApp',
  );
}
