# -*- coding: utf-8 -*-
"""TrainModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PeLKCfUmCkJgktIRJFqk1eB_h7w4vCrt
"""

# 0. Install the required library for Colab/Jupyter
!pip install m2cgen

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import m2cgen as m2c
# ==========================================
# (A) Load the data and split it
# ==========================================
excel_path = "synthetic_seizure_dataset_20k.xlsx"
df = pd.read_excel(excel_path, sheet_name="encoded")

# Check that all required columns exist to avoid training errors
expected_cols = ["HR", "HRV", "Medication", "Symptoms", "Sleep", "Stress", "risk"]
missing = [c for c in expected_cols if c not in df.columns]

if missing:
    raise ValueError(f"Missing required columns: {missing}")

# Separate input features from the output label
X = df[["HR", "HRV", "Medication", "Symptoms", "Sleep", "Stress"]].astype(np.float32).values
y = df["risk"].astype(int).values

# First split: reserve 20% as the final test set
X_temp, X_test, y_temp, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,  # Fix randomness so the same split is produced every time
    stratify=y
)

# Second split: split the remaining 80% into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(
    X_temp,
    y_temp,
    test_size=0.25,   # 25% of the remaining data becomes validation data
    random_state=42,  # Fix randomness again for reproducible results
    stratify=y_temp
)

print(f"Data split - Train: {X_train.shape[0]} | Validation: {X_val.shape[0]} | Test: {X_test.shape[0]}")
print("-" * 30)

from google.colab import drive
drive.mount('/content/drive')

"""Final Validation Accuracy: 94.8%

Final Recall: 90.1%

 Model Validation Accuracy: 99.0%

 Model Validation Accuracy: 94.8%

Training completed successfully.

Training log saved as training_log.csv
Model exported as seizure_model.tflite

"""

# ==========================================
# (B) Train the teacher model (Random Forest)
# ==========================================
rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf.fit(X_train, y_train)

# Measure model accuracy on the validation set
val_pred = rf.predict(X_val)
print("Validation accuracy:", accuracy_score(y_val, val_pred))

## ==========================================
# (C) Build and train the student model (Neural Network)
# Why? Because converting the model into a deployable format for applications
# is not feasible with decision trees, as they are large and not suitable for mobile apps
# ==========================================
# Generate predictions on the hidden test set
rf_test_pred = rf.predict(X_test)

print("\n" + "=" * 40)
print("Final Model Evaluation on the Test Set")
print("=" * 40)

# 1. Overall accuracy
print(f"Overall Accuracy: {accuracy_score(y_test, rf_test_pred):.4f}\n")

# 2. Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_test_pred))
print("\n")

# 3. Full classification report: precision, recall, and F1-score
print("Classification Report:")
print(classification_report(y_test, rf_test_pred))
print("=" * 40 + "\n")

# ==========================================
# (D) Convert the model for mobile deployment
# ==========================================
# Engineering note:
# Instead of using a heavier AI format like TFLite inside the app,
# this approach uses m2cgen to convert the trained Random Forest model
# directly into pure Dart code.
#
# The generated Dart file contains the mathematical decision rules learned
# by the 300 trees. In Flutter, this can run like a normal function without
# requiring TensorFlow Lite or internet access.

print("Converting the model to native Dart code. This may take some time because the model is large...")

# This converts the trained Random Forest model into native Dart code.
# The generated code can be used directly in Flutter.
dart_code = m2c.export_to_dart(rf)

# Save the generated Dart code to a file
# In the app, pass the six sensor/input values as a List<double>
# to the generated score() function to get the risk prediction.
dart_file_path = "rf_model.dart"

with open(dart_file_path, "w", encoding="utf-8") as f:
    f.write(dart_code)

print(f"Done. The model has been saved as: {dart_file_path}")

# ==========================================
# Professional Testing Cell for Random Forest
# ==========================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    roc_curve
)

class_names = ["Low Risk", "High Risk"]
feature_names = ["HR", "HRV", "Medication", "Symptoms", "Sleep", "Stress"]


# ------------------------------------------
# 1. Predictions
# ------------------------------------------
val_pred = rf.predict(X_val)
test_pred = rf.predict(X_test)

val_probs = rf.predict_proba(X_val)[:, 1]
test_probs = rf.predict_proba(X_test)[:, 1]


# ------------------------------------------
# 2. Professional confusion matrix plot
# ------------------------------------------
def plot_confusion_matrix_professional(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    cm_percent = cm / cm.sum(axis=1, keepdims=True) * 100

    fig, ax = plt.subplots(figsize=(7, 6))

    image = ax.imshow(cm_percent, interpolation="nearest", cmap="Blues")

    cbar = fig.colorbar(image, ax=ax)
    cbar.set_label("Percentage within True Class", rotation=270, labelpad=18)

    ax.set_title(title, fontsize=15, fontweight="bold", pad=14)
    ax.set_xlabel("Predicted Label", fontsize=12, labelpad=10)
    ax.set_ylabel("True Label", fontsize=12, labelpad=10)

    ax.set_xticks(np.arange(len(class_names)))
    ax.set_yticks(np.arange(len(class_names)))
    ax.set_xticklabels(class_names, fontsize=11)
    ax.set_yticklabels(class_names, fontsize=11)

    threshold = cm_percent.max() / 2

    for i in range(cm.shape[0]):
        for j in range(cm.shape[1]):
            text_color = "white" if cm_percent[i, j] > threshold else "black"
            ax.text(
                j,
                i,
                f"{cm[i, j]}\n({cm_percent[i, j]:.1f}%)",
                ha="center",
                va="center",
                color=text_color,
                fontsize=12,
                fontweight="bold"
            )

    ax.set_ylim(len(class_names) - 0.5, -0.5)

    for spine in ax.spines.values():
        spine.set_visible(False)

    ax.set_xticks(np.arange(len(class_names) + 1) - 0.5, minor=True)
    ax.set_yticks(np.arange(len(class_names) + 1) - 0.5, minor=True)
    ax.grid(which="minor", color="white", linestyle="-", linewidth=2)
    ax.tick_params(which="minor", bottom=False, left=False)

    plt.tight_layout()
    plt.show()

    return cm


# ------------------------------------------
# 3. Evaluation function
# ------------------------------------------
def evaluate_random_forest(split_name, y_true, y_pred, y_prob):
    print("\n" + "=" * 55)
    print(f"Random Forest Evaluation on {split_name} Set")
    print("=" * 55)

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average="weighted", zero_division=0)
    recall = recall_score(y_true, y_pred, average="weighted", zero_division=0)
    f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)

    print(f"Accuracy : {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall   : {recall:.4f}")
    print(f"F1-score : {f1:.4f}")

    try:
        auc = roc_auc_score(y_true, y_prob)
        print(f"ROC-AUC  : {auc:.4f}")
    except ValueError:
        print("ROC-AUC  : Not available")

    print("\nClassification Report:")
    print(classification_report(
        y_true,
        y_pred,
        target_names=class_names,
        zero_division=0
    ))

    cm = plot_confusion_matrix_professional(
        y_true,
        y_pred,
        f"Random Forest Confusion Matrix - {split_name} Set"
    )

    print("Confusion Matrix:")
    print(cm)

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1_score": f1,
        "roc_auc": auc if "auc" in locals() else None,
        "confusion_matrix": cm
    }


# ------------------------------------------
# 4. Validation evaluation
# ------------------------------------------
val_metrics = evaluate_random_forest(
    "Validation",
    y_val,
    val_pred,
    val_probs
)


# ------------------------------------------
# 5. Test evaluation
# ------------------------------------------
test_metrics = evaluate_random_forest(
    "Test",
    y_test,
    test_pred,
    test_probs
)


# ------------------------------------------
# 6. ROC curve
# ------------------------------------------
fpr, tpr, thresholds = roc_curve(y_test, test_probs)
test_auc = roc_auc_score(y_test, test_probs)

plt.figure(figsize=(7, 5))
plt.plot(fpr, tpr, linewidth=2.5, label=f"Random Forest AUC = {test_auc:.4f}")
plt.plot([0, 1], [0, 1], linestyle="--", linewidth=1.5, label="Random Guess")
plt.xlabel("False Positive Rate", fontsize=12)
plt.ylabel("True Positive Rate", fontsize=12)
plt.title("Random Forest ROC Curve - Test Set", fontsize=14, fontweight="bold")
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()


# ------------------------------------------
# 7. Feature importance
# ------------------------------------------
importances = rf.feature_importances_

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

print("\nFeature Importance:")
print(importance_df)

plt.figure(figsize=(7, 5))
plt.bar(importance_df["Feature"], importance_df["Importance"])
plt.xlabel("Feature", fontsize=12)
plt.ylabel("Importance", fontsize=12)
plt.title("Random Forest Feature Importance", fontsize=14, fontweight="bold")
plt.xticks(rotation=45)
plt.grid(axis="y", alpha=0.3)
plt.tight_layout()
plt.show()